[package]
name = "tskv-rs"
version = "0.1.0"
authors = ["Sergey Kacheev <uo0@ya.ru>"]

[dependencies]
regex = "1.5.5"
memchr = { version = "1.0", default-features = false }

[profile.release]
panic = 'abort'
